<div class="row">

    <div class="span4">
        <h3><a href="http://www.4mation.com.au/" target="_blank" title="Link to the 4mation Technologies website" >4mation Technologies</a></h3>
        <p><a href="http://www.4mation.com.au/" target="_blank" title="Link to the 4mation Technologies website" >
        <?php 
        // Using DkcwdZf2Munee view helper to resize and cache image
        echo $this->muneeImg(
                 $this->basepath() . '/images/4mation.jpg', 
                 'w[120]h[52]', 
                 array(
                    'alt'   => '4mation Technologies Logo',
                    'title' => '4mation Technologies sponsor Zend Framework Sydney User Group meetings'
                 )
             ); 
        ?>        
        </a></p>
        <p>Based in Sydney, 4mation's team has grown steadily over the last 10 years, and now consists of 25 professional web designers and PHP developers. </p> <p>With a proven track record of creating robust, high quality solutions, 4mation's digital producers and project managers can guide you through every step of the development process. Whether it's development of a new project, or rescuing a struggling existing website or system, 4mation can help.</p><p>4mation Technologies support the Zend Framework Sydney user group by offering us use of their fantastic premises for our monthly meetings.</p> <p><a href="http://www.4mation.com.au/" target="_blank" title="Link to the 4mation Technologies website" >View their website &raquo;</a></p>
    </div>    
        
    <div class="span4">
        <h3><a href="http://www.anchor.com.au/" target="_blank" title="Link to the Anchor Systems website" >Anchor Systems</a></h3>
        <p><a href="http://www.anchor.com.au/" target="_blank" title="Link to the Anchor Systems website" >
        <?php 
        // Using DkcwdZf2Munee view helper to resize and cache image
        echo $this->muneeImg(
                 $this->basepath() . '/images/anchor.jpg', 
                 'w[120]h[52]', 
                 array(
                    'alt'   => 'Anchor Systems Logo',
                    'title' => 'Anchor Systems sponsor Zend Framework Sydney User Group meetings'
                 )
             ); 
        ?>
        </a></p>
        <p>Anchor's team are well known in the Sydney web development community for their awesome service and near immediate availability.  Beyond this Anchor's reputation for generosity in support of local community initiatives is well regarded and upheld regularly. </p> <p>As a provider of managed hosting services with more than 3000 customers on board, Anchor strives to ensure you get to talk with a real person without having to go through automated options and endless music loops.</p><p>Anchor Systems supported the Zend Framework Sydney user group by providing us with food and refreshments for our meetup on 13th February 2013.</p> <p><a href="http://www.anchor.com.au/" target="_blank" title="Link to the Anchor Systems website" >View their website &raquo;</a></p>
    </div>    
    
    <div class="span4">
        <p style="margin-top:20px;">
        <?php 
        // Using DkcwdZf2Munee view helper to resize and cache image
        echo $this->muneeImg(
                 $this->basePath() . '/images/2013-02-13-zfsyd.jpg', 
                 'w[345]h[344]',
                 array(                    
                    'alt'   => 'Zend Framework Sydney User Group meeting',
                    'title' => 'Zend Framework Sydney User Group meeting'
                )
            );
        ?>
        </p>        
    </div>    
   
</div>   
