<div class="row">

        <div class="span4">
            <h2><a href="http://meetup.zfsyd.org" target="_blank" title="Link to the ZFSyd.org meetup pages" ><?php echo $this->translate('Events') ?></a></h2>
            <p>We meet every month to share experiences and keep up to date with the latest ZF news.</p>
            <p><a class="btn btn-success" href="http://meetup.zfsyd.org" target="_blank" title="Link to the ZFSyd.org meetup pages">Find out about upcoming events &raquo;</a></p>
        </div>    
        
        <div class="span4">
            <h2><a href="https://github.com/zfsyd" target="_blank" title="Link to the ZFSyd.org GitHub.com page" ><?php echo $this->translate('Collaboration') ?></a></h2>
            <p>Our place to work together on projects, share tips and showcase efforts from hack days.</p>
            <p><a class="btn btn-success" href="https://github.com/zfsyd" target="_blank" title="Link to the ZFSyd.org GitHub.com page">Visit ZFSyd on GitHub.com &raquo;</a></p>
       </div>
    
       <div class="span4">
            <h2><a href="<?php echo $this->basePath() ?>/sponsors" title="Link to the ZFSyd.org Sponsors page" ><?php echo $this->translate('Sponsors') ?></a></h2>
            <p>Our monthly meetings are supported by some very generous sponsors.</p>
            <p><a class="btn btn-success" href="<?php echo $this->basePath() ?>/sponsors" title="Link to the ZFSyd.org Sponsors page">Learn about our sponsors &raquo;</a></p>
       </div>
   
    </div>   